include: "rules/common.smk"
include: "rules/qc.smk"
include: "rules/align.smk"
include: "rules/bw.smk"
include: "rules/deg.smk"
include: "rules/go.smk"
include: "rules/gsea.smk"

qc = ["results/qc/multiqc/multiqc_report.html"]
out_files = qc

if config['addons']['deseq2']:
	out_files += expand("results/deg/{contrast}.xls", contrast = contrasts) + ["results/deg/pca.pdf"]

if config['addons']['star']:
	out_files += expand("results/bw/{sample}.bw", sample = samples)

if config['addons']['go']:
	out_files += expand("results/go/{contrast}.xls", contrast = contrasts)

if config['addons']['gsea']:
	out_files += expand("results/gsea/{contrast}_{collection}.done", contrast = contrasts, collection = config['gsea']['collections'].split(","))

rule all:
	input:
		out_files

onsuccess:
	shell("if command -v telegram-notify; then telegram-notify --success --text \'Snakemake:rnaseq:{} Completed\'; fi".format(foldername.replace("_", "\\_")))

onerror:
	shell("if command -v telegram-notify; then telegram-notify --error --text \'Snakemake:rnaseq:{} Failed\'; fi".format(foldername.replace("_", "\\_")))
